//go:build !ignore_autogenerated

/*
Copyright 2026 UndermountainCC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgent) DeepCopyInto(out *HermesAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgent.
func (in *HermesAgent) DeepCopy() *HermesAgent {
	if in == nil {
		return nil
	}
	out := new(HermesAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HermesAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentClusterRoleBinding) DeepCopyInto(out *HermesAgentClusterRoleBinding) {
	*out = *in
	out.RoleRef = in.RoleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentClusterRoleBinding.
func (in *HermesAgentClusterRoleBinding) DeepCopy() *HermesAgentClusterRoleBinding {
	if in == nil {
		return nil
	}
	out := new(HermesAgentClusterRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentDashboardIngress) DeepCopyInto(out *HermesAgentDashboardIngress) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(HermesAgentDashboardIngressTLS)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentDashboardIngress.
func (in *HermesAgentDashboardIngress) DeepCopy() *HermesAgentDashboardIngress {
	if in == nil {
		return nil
	}
	out := new(HermesAgentDashboardIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentDashboardIngressTLS) DeepCopyInto(out *HermesAgentDashboardIngressTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentDashboardIngressTLS.
func (in *HermesAgentDashboardIngressTLS) DeepCopy() *HermesAgentDashboardIngressTLS {
	if in == nil {
		return nil
	}
	out := new(HermesAgentDashboardIngressTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentDashboardService) DeepCopyInto(out *HermesAgentDashboardService) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentDashboardService.
func (in *HermesAgentDashboardService) DeepCopy() *HermesAgentDashboardService {
	if in == nil {
		return nil
	}
	out := new(HermesAgentDashboardService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentDashboardSpec) DeepCopyInto(out *HermesAgentDashboardSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Service.DeepCopyInto(&out.Service)
	in.Ingress.DeepCopyInto(&out.Ingress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentDashboardSpec.
func (in *HermesAgentDashboardSpec) DeepCopy() *HermesAgentDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(HermesAgentDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentGateway) DeepCopyInto(out *HermesAgentGateway) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentGateway.
func (in *HermesAgentGateway) DeepCopy() *HermesAgentGateway {
	if in == nil {
		return nil
	}
	out := new(HermesAgentGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentGatewayStatus) DeepCopyInto(out *HermesAgentGatewayStatus) {
	*out = *in
	if in.LastProbedAt != nil {
		in, out := &in.LastProbedAt, &out.LastProbedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentGatewayStatus.
func (in *HermesAgentGatewayStatus) DeepCopy() *HermesAgentGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(HermesAgentGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentLLMProvider) DeepCopyInto(out *HermesAgentLLMProvider) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentLLMProvider.
func (in *HermesAgentLLMProvider) DeepCopy() *HermesAgentLLMProvider {
	if in == nil {
		return nil
	}
	out := new(HermesAgentLLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentLLMStatus) DeepCopyInto(out *HermesAgentLLMStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentLLMStatus.
func (in *HermesAgentLLMStatus) DeepCopy() *HermesAgentLLMStatus {
	if in == nil {
		return nil
	}
	out := new(HermesAgentLLMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentList) DeepCopyInto(out *HermesAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HermesAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentList.
func (in *HermesAgentList) DeepCopy() *HermesAgentList {
	if in == nil {
		return nil
	}
	out := new(HermesAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HermesAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentNetworkPolicy) DeepCopyInto(out *HermesAgentNetworkPolicy) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]networkingv1.NetworkPolicyIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]networkingv1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyTypes != nil {
		in, out := &in.PolicyTypes, &out.PolicyTypes
		*out = make([]networkingv1.PolicyType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentNetworkPolicy.
func (in *HermesAgentNetworkPolicy) DeepCopy() *HermesAgentNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(HermesAgentNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentRBAC) DeepCopyInto(out *HermesAgentRBAC) {
	*out = *in
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]HermesAgentRoleBinding, len(*in))
		copy(*out, *in)
	}
	if in.ClusterRoleBindings != nil {
		in, out := &in.ClusterRoleBindings, &out.ClusterRoleBindings
		*out = make([]HermesAgentClusterRoleBinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentRBAC.
func (in *HermesAgentRBAC) DeepCopy() *HermesAgentRBAC {
	if in == nil {
		return nil
	}
	out := new(HermesAgentRBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentRoleBinding) DeepCopyInto(out *HermesAgentRoleBinding) {
	*out = *in
	out.RoleRef = in.RoleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentRoleBinding.
func (in *HermesAgentRoleBinding) DeepCopy() *HermesAgentRoleBinding {
	if in == nil {
		return nil
	}
	out := new(HermesAgentRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentSpec) DeepCopyInto(out *HermesAgentSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LLMProviders != nil {
		in, out := &in.LLMProviders, &out.LLMProviders
		*out = make([]HermesAgentLLMProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]HermesAgentGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RBAC.DeepCopyInto(&out.RBAC)
	in.Dashboard.DeepCopyInto(&out.Dashboard)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentSpec.
func (in *HermesAgentSpec) DeepCopy() *HermesAgentSpec {
	if in == nil {
		return nil
	}
	out := new(HermesAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentStatus) DeepCopyInto(out *HermesAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]HermesAgentGatewayStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.LLMProvider = in.LLMProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentStatus.
func (in *HermesAgentStatus) DeepCopy() *HermesAgentStatus {
	if in == nil {
		return nil
	}
	out := new(HermesAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HermesAgentStorage) DeepCopyInto(out *HermesAgentStorage) {
	*out = *in
	in.PersistentVolumeClaim.DeepCopyInto(&out.PersistentVolumeClaim)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HermesAgentStorage.
func (in *HermesAgentStorage) DeepCopy() *HermesAgentStorage {
	if in == nil {
		return nil
	}
	out := new(HermesAgentStorage)
	in.DeepCopyInto(out)
	return out
}
